### ISSUE TITLE
possible game hang caused by cards and jester

### ISSUE THREAD

**Issue by ShadowRocks2** [Asonyx/LCTarrotCard#2]
game keeps getting stuck going to a planet and this is the error i get

LCTarrotCard.Networker.PopOrSpawnJesterServerRpc (System.Single popDelay) (at <435b562d68c1460e9c1da4907176a91d>:IL_014E)
LCTarrotCard.Networker.__rpc_handler_900698346 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <435b562d68c1460e9c1da4907176a91d>:IL_0049)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkMessageManager:ReceiveMessage(FastBufferReader, NetworkContext&, NetworkMessageManager)
Unity.Netcode.NetworkMessageManager:HandleMessage(NetworkMessageHeader&, FastBufferReader, UInt64, Single, Int32)
Unity.Netcode.NetworkMessageManager:ProcessIncomingMessageQueue()
Unity.Netcode.NetworkManager:NetworkUpdate(NetworkUpdateStage)
Unity.Netcode.NetworkUpdateLoop:RunNetworkUpdateStage(NetworkUpdateStage)
Unity.Netcode.<>c:<CreateLoopSystem>b__0_0()

**Comment by Asonyx** [comment]
Hi, could you send me little more, because I can hardly identify the problem with juste what you sent here. If you can please send me a screenshot of the console when the error happens (a screenshot of the full error stack trace) and the mods you use (a r2modman profile code is enough if you can). 
If you could send me this here or on discord (asonyx) I would appreciate it.

**Comment by ShadowRocks2** [comment]
i can give you the log and code
Code: 019233f2-56a0-9490-2660-95daaf4ceb5b
Log: attached below
[My Log.txt](https://github.com/user-attachments/files/17165892/My.Log.txt)

**Comment by Asonyx** [comment]
Ok thanks, I see now why it happened. I will patch it for the next update
